<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup></PropertyGroup>
  <ItemGroup><ProjectReference Include="../WireMarkerInspection.Domain/WireMarkerInspection.Domain.csproj" /><ProjectReference Include="../WireMarkerInspection.Application/WireMarkerInspection.Application.csproj" /></ItemGroup>
</Project>

